### ISSUE TITLE
navigating to waypoints does not work

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/robot_smach_states#9]
Navigate to observe ->  waypoint (GUI)

[ERROR] [WallTime: 1419361008.436064] InvalidUserCodeError: Could not execute state 'GET_PLAN' of type '<robot_smach_states.navigation.navigation.getPlan object at 0x408f390>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/home/rein/ros/hydro/system/src/robot_smach_states/src/robot_smach_states/navigation/navigation.py", line 34, in execute
    constraint = self.constraint_function()
  File "/home/rein/ros/hydro/system/src/robot_smach_states/src/robot_smach_states/navigation/navigate_to_observe.py", line 36, in generateConstraint
    ch.append(ch[0])
IndexError: list index out of range

[ERROR] [WallTime: 1419361008.436986] InvalidStateError: Could not execute child state 'NAVIGATE': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/concurrence.py", line 326, in _state_runner
    self._remappings[label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7fe9dc057b48>

**Comment by rokusottervanger** [comment]
I added a distinction between navigating to a waypoint or some other entity in the action server. This either calls NavigateToObserve (previously always called) or NavigateToWaypoint, in case the goal entity type is waypoint. I tested and it should be fixed.
